use clap::{Args, CommandFactory};
use clap_complete::{Shell, generate};
use std::io;

use crate::commands::Cli;
use crate::error::VexResult;

#[derive(Args, Debug)]
/// Generate shell completion scripts
///
/// Outputs the completion script for the specified shell to standard output.
/// Supported shells include: bash, zsh, fish, powershell, and elvish.
///
/// Vex provides advanced dynamic completions for Bash, Zsh, and Fish,
/// allowing you to seamlessly autocomplete your saved configuration names
/// when using commands like `exec`, `edit`, `rename`, and `rm`.
///
/// # Examples
///
/// Load completions for the current session (Bash):
///   source <(vex completions bash)
///
/// Install completions permanently (Bash):
///   vex completions bash > ~/.local/share/bash-completion/completions/vex
///
/// Install completions (Zsh):
///   vex completions zsh > /usr/local/share/zsh/site-functions/_vex
///
/// Install completions (Fish):
///   vex completions fish > ~/.config/fish/completions/vex.fish
pub struct CompletionsArgs {
    /// Shell type to generate completions for
    pub shell: clap_complete::Shell,
}

pub fn completions_command(shell: Shell) -> VexResult<()> {
    let mut cmd = Cli::command();
    // Get the binary name (typically "vex")
    let bin_name = cmd.get_name().to_string();

    // Use eprintln! to output log to stderr so it doesn't break `source <(vex completions bash)`
    eprintln!("Generating completion script for {}", bin_name);

    // Generate base completion script provided by clap
    generate(shell, &mut cmd, bin_name.clone(), &mut io::stdout());

    // Add Vex's custom dynamic completion logic for supported shells
    match shell {
        Shell::Bash => print_bash_dynamic_completion(&bin_name),
        Shell::Zsh => print_zsh_dynamic_completion(&bin_name),
        Shell::Fish => print_fish_dynamic_completion(&bin_name),
        _ => {
            eprintln!(
                "# Note: Dynamic config name completion not yet implemented for {:?}",
                shell
            );
        }
    }

    Ok(())
}

fn print_bash_dynamic_completion(bin_name: &str) {
    println!(
        r#"
# === Dynamic configuration name completion ===
# Extract configuration names dynamically from vex list output
_vex_get_configs() {{
    {bin_name} list 2>/dev/null | grep ' - ' | awk '{{print $1}}'
}}

# Extract cached hash entries from vex cache list output (hashes are emitted on
# their own line, full 64 hex chars)
_vex_get_cache_hashes() {{
    {bin_name} cache list 2>/dev/null | grep -E '^[0-9a-f]{{64}}$'
}}

# Save original completion function generated by clap
_vex_original=$(declare -f _vex)
eval "${{_vex_original/_vex/_vex_base}}"

# Enhanced completion function wrapper
_vex() {{
    local cur prev subcmd
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    # Check if we are at a position where configuration name completion is needed
    if [[ ${{COMP_CWORD}} -ge 2 ]]; then
        subcmd="${{COMP_WORDS[1]}}"
        case "$subcmd" in
            exec|rm|edit)
                # First argument for exec, rm, and edit is the configuration name
                if [[ ${{COMP_CWORD}} -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "$(_vex_get_configs)" -- "${{cur}}") )
                    return 0
                fi
                ;;
            rename)
                # First argument for rename is the old configuration name
                if [[ ${{COMP_CWORD}} -eq 2 ]]; then
                    COMPREPLY=( $(compgen -W "$(_vex_get_configs)" -- "${{cur}}") )
                    return 0
                fi
                ;;
            push)
                # Second argument for push is the local configuration name
                if [[ ${{COMP_CWORD}} -eq 3 ]]; then
                    COMPREPLY=( $(compgen -W "$(_vex_get_configs)" -- "${{cur}}") )
                    return 0
                fi
                ;;
            resource)
                # vex resource <add|rm|list> <CONFIG_NAME>
                if [[ ${{COMP_CWORD}} -eq 3 ]]; then
                    local action="${{COMP_WORDS[2]}}"
                    case "$action" in
                        add|rm|list)
                            COMPREPLY=( $(compgen -W "$(_vex_get_configs)" -- "${{cur}}") )
                            return 0
                            ;;
                    esac
                fi
                ;;
            cache)
                # vex cache <info|rm> <HASH>
                if [[ ${{COMP_CWORD}} -eq 3 ]]; then
                    local action="${{COMP_WORDS[2]}}"
                    case "$action" in
                        info|rm)
                            COMPREPLY=( $(compgen -W "$(_vex_get_cache_hashes)" -- "${{cur}}") )
                            return 0
                            ;;
                    esac
                fi
                ;;
        esac
    fi

    # Fall back to base completion for flags and other commands
    _vex_base "$@"
}}

# Re-bind the enhanced completion function to the binary
complete -F _vex {bin_name}
"#,
        bin_name = bin_name
    );
}

fn print_zsh_dynamic_completion(bin_name: &str) {
    println!(
        r#"
# === Zsh dynamic configuration name completion ===
# Fetch and format configuration names for Zsh _describe
_vex_configs() {{
    local configs
    configs=($({bin_name} list 2>/dev/null | grep ' - ' | awk '{{print $1}}'))
    _describe 'configurations' configs
}}

# Fetch cached hash entries for Zsh _describe
_vex_cache_hashes() {{
    local hashes
    hashes=($({bin_name} cache list 2>/dev/null | grep -E '^[0-9a-f]{{64}}$'))
    _describe 'cache objects' hashes
}}

# Enhanced _vex function replacing the default clap implementation
_vex() {{
    local line state
    local -a cmds

    _arguments -C \
        "1: :->cmds" \
        "*::arg:->args"

    case "$state" in
        cmds)
            # Define subcommands and their descriptions
            cmds=(
                "save:Save QEMU configuration"
                "rename:Rename a saved QEMU configuration"
                "rm:Remove a saved QEMU configuration"
                "list:List all saved QEMU configurations"
                "print:Print details of a configuration"
                "pull:Pull a shared configuration from the remote registry"
                "push:Push a local configuration to the remote registry"
                "exec:Execute a saved QEMU configuration"
                "completions:Generate shell completion scripts"
                "edit:Edit a saved QEMU configuration"
                "resource:Manage resources bound to a configuration"
                "cache:Manage the resource cache"
                "hub:Browse and install entries from the Vex Hub"
                "tui:Launch the interactive TUI"
            )
            _describe -t commands 'vex command' cmds
            ;;
        args)
            # Switch based on the parsed subcommand
            case $line[1] in
                exec|rm|edit)
                    # Provide dynamic completion for the first argument
                    if (( CURRENT == 2 )); then
                        _vex_configs
                    fi
                    ;;
                rename)
                    if (( CURRENT == 2 )); then
                        _vex_configs
                    fi
                    ;;
                push)
                    if (( CURRENT == 3 )); then
                        _vex_configs
                    fi
                    ;;
                resource)
                    # vex resource <add|rm|list> <CONFIG_NAME>
                    if (( CURRENT == 3 )); then
                        case $line[2] in
                            add|rm|list)
                                _vex_configs
                                ;;
                        esac
                    fi
                    ;;
                cache)
                    # vex cache <info|rm> <HASH>
                    if (( CURRENT == 3 )); then
                        case $line[2] in
                            info|rm)
                                _vex_cache_hashes
                                ;;
                        esac
                    fi
                    ;;
            esac
            ;;
    esac
}}
"#,
        bin_name = bin_name
    );
}

fn print_fish_dynamic_completion(bin_name: &str) {
    println!(
        r#"
# === Fish dynamic configuration name completion ===
# Helper function to get the list of saved configurations
function __vex_configs
    {bin_name} list 2>/dev/null | grep ' - ' | awk '{{print $1}}'
end

# Helper function to get cached resource hashes
function __vex_cache_hashes
    {bin_name} cache list 2>/dev/null | grep -E '^[0-9a-f]{{64}}$'
end

# Clear existing file completions for vex to rely on dynamic logic
complete -c vex -f

# Add configuration name completion for specific subcommands
complete -c vex -n "__fish_seen_subcommand_from exec" -a "(__vex_configs)" -d "Configuration name"
complete -c vex -n "__fish_seen_subcommand_from rm" -a "(__vex_configs)" -d "Configuration name"
complete -c vex -n "__fish_seen_subcommand_from edit" -a "(__vex_configs)" -d "Configuration name"
complete -c vex -n "__fish_seen_subcommand_from push; and test (count (commandline -opc)) -eq 3" -a "(__vex_configs)" -d "Local configuration name"

# Add configuration name completion for the first argument of rename
complete -c vex -n "__fish_seen_subcommand_from rename; and not __fish_seen_subcommand_from (__vex_configs)" -a "(__vex_configs)" -d "Old configuration name"

# vex resource <add|rm|list> <CONFIG_NAME>
complete -c vex -n "__fish_seen_subcommand_from resource; and __fish_seen_subcommand_from add rm list; and test (count (commandline -opc)) -eq 3" -a "(__vex_configs)" -d "Configuration name"

# vex cache <info|rm> <HASH>
complete -c vex -n "__fish_seen_subcommand_from cache; and __fish_seen_subcommand_from info rm; and test (count (commandline -opc)) -eq 3" -a "(__vex_cache_hashes)" -d "Cache object hash"
"#,
        bin_name = bin_name
    );
}
