use clap::Args;
use std::env;
use std::fs;
use std::io::Write;
use std::process::Command;
use tempfile::Builder;

use crate::commands::exec::exec_command;
use crate::config::{QemuConfig, config_file, validate_config, validate_config_name};
use crate::error::{VexError, VexResult};
use crate::utils::io::prompt_user_default_no;

#[derive(Args, Debug)]
pub struct EditArgs {
    pub name: String,
}

pub fn edit_command(name: String) -> VexResult<()> {
    validate_config_name(&name)?;
    let config_path = config_file(&name)?;
    if !config_path.exists() {
        return Err(VexError::ConfigNotFound { name: name.clone() });
    }

    let original_content = fs::read_to_string(&config_path).map_err(|e| VexError::IoError {
        path: config_path.clone(),
        operation: "read config file".to_string(),
        source: e,
    })?;

    let mut temp_file = Builder::new()
        .prefix("vex-edit-")
        .suffix(".json")
        .tempfile()
        .map_err(|e| VexError::IoError {
            path: std::path::PathBuf::from("/tmp"),
            operation: "create temporary file".to_string(),
            source: e,
        })?;

    temp_file
        .write_all(original_content.as_bytes())
        .map_err(|e| VexError::IoError {
            path: std::path::PathBuf::from("temp file"),
            operation: "write temporary file".to_string(),
            source: e,
        })?;

    let temp_path = temp_file.into_temp_path();

    let editor = env::var("EDITOR").unwrap_or_else(|_| {
        if cfg!(windows) {
            "notepad".to_string()
        } else {
            "vim".to_string()
        }
    });

    // $EDITOR is trusted local input controlled by the user. The temp path
    // is generated by the `tempfile` crate and is not user-controllable.
    let status = if cfg!(windows) {
        Command::new("cmd")
            .arg("/C")
            .arg(format!("{} \"{}\"", editor, temp_path.display()))
            .status()
    } else {
        Command::new("sh")
            .arg("-c")
            .arg(format!("{} \"{}\"", editor, temp_path.display()))
            .status()
    }
    .map_err(|e| VexError::IoError {
        path: std::path::PathBuf::from(&editor),
        operation: format!("open editor: {}", editor),
        source: e,
    })?;

    if !status.success() {
        return Err(VexError::EditorFailed {
            editor,
            exit_code: status.code(),
        });
    }

    let edited_content = fs::read_to_string(&temp_path).map_err(|e| VexError::IoError {
        path: temp_path.to_path_buf(),
        operation: "read edited file".to_string(),
        source: e,
    })?;

    if original_content == edited_content {
        println!("No changes made to '{}'.", name);
        return Ok(());
    }

    match serde_json::from_str::<QemuConfig>(&edited_content) {
        Ok(new_config) => {
            validate_config(&new_config)?;
            let formatted_json = serde_json::to_string_pretty(&new_config)
                .map_err(|e| VexError::ConfigSerializeFailed { source: e })?;
            fs::write(&config_path, formatted_json).map_err(|e| VexError::IoError {
                path: config_path.clone(),
                operation: "save updated config".to_string(),
                source: e,
            })?;
            println!("Configuration '{}' updated successfully.", name);

            println!("\nDo you want to test-run this configuration now? [y/N]");
            if prompt_user_default_no()? {
                println!("Starting test-run for '{}'...\n", name);
                exec_command(name, false, false)?;
            }
        }
        Err(e) => {
            return Err(VexError::ConfigParseFailed { source: e });
        }
    }

    Ok(())
}
